name: Basic PR Tests

on: [pull_request]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Pull library deps
        run: forge update

      - name: Run forge tests
<<<<<<< HEAD
        run: ./test.sh -p deep
=======
        run: ./test.sh -r 100000
>>>>>>> 41eb11a (feat: switched to forge)
